service: solo-node-challenge

provider:
 name: aws
 runtime: nodejs14.x
 stage: dev
 region: us-east-1

functions:
 server:
   handler: lambda.server
   timeout: 30
   events:
     - http: ANY /
     - http: 'ANY {proxy+}'